### ISSUE TITLE
Download all only works after submission deadline ends

### ISSUE THREAD

**Issue by Conzel** [infomark-org/infomark-ui#6]
**Expected Behaviour:** Clicking on the latest exercise sheet and then clicking "Download All" starts a download with a zip file of all the current exercises handed in.
**Actual Behaviour:** "Download All" instead returns a "File not found". After the submission deadline has ended, the expected behaviour occurs.
**Steps to reproduce:** 
- Click as tutor on the latest exercise sheet, for which the submission deadline has not passed yet. 
- Click "Download All".

**Comment by PatWie** [comment]
This is expected behavior on the backend. As these files are not zipped on-the-fly but after the deadline has finished in a separate thread. This button should be disabled beforehand as the uploaded solutions might change anyway.

*Reference*
https://github.com/infomark-org/infomark/blob/66373016d9dac20eea3faf3f692b13dcd788daac/api/server.go#L98-L102

**Comment by Conzel** [comment]
Small update: The same error persists after the Submission has ended (tested today, 10:17 AM, submission was closed at 00:00 AM today).

**Comment by PatWie** [comment]
What's the output of
```bash
./infomark console configuration test infomark-config.yml
```

**Comment by ogrady** [comment]
That would be 

```
user@server:/var/www/infomark-staging/app$ ./infomark console configuration test infomark-config.yml

  Test configuration
    ✓ read configuration from file

  Test services
    ✓ connect to postgres db
    ✓ connect to redis url
    ✓ connect to rabbit mq

  Test paths
    1) common path readable

    stat /var/www/storage/infomark_data/files/common: permission denied
    1) upload path writeable

    open /var/www/storage/infomark_data/files/uploads/.check_if_writeable: permission denied
    1) generated_files path writeable

    open /var/www/storage/infomark_data/files/generated_files/.check_if_writeable: permission denied
    1) Read privacy Statement from /var/www/storage/infomark_data/files/common/privacy_statement.md

    stat /var/www/storage/infomark_data/files/common/privacy_statement.md: permission denied
```

**Comment by PatWie** [comment]
And there is your issue. Please make `/var/www/storage/infomark_data/files` writable, eg.
using 

```bash
chown -R <infomark-user>:<infomark-group> /var/www/storage/infomark_data/file
```

or at least 
```bash
chmod -R o+w /var/www/storage/infomark_data/file
```` 

(better use `chown`). Run the config-test again and make sure this check is green for all tests. The `privacy_statement` check is optional, but you should create such a `privacy_statement.md` file.

See the guide https://infomark.org/guides/overview/ section *Run*.

Please note, if these directories are writeable, then Infomark will **retry** automatically creating those files.

**Comment by PatWie** [comment]
fixed in https://github.com/infomark-org/infomark/pull/5
